notifications:
 email:
  - finchjavar@yahoo.com
stages:
 - frontend
 - backend
 - deployment
dist: trusty
sudo: required
branches:
 only:
  - master
jobs:
 include:
  - stage: frontend
    language: node_js
    node_js:
     - 10
    addons:
     chrome: stable
    before_script:
     - cd /
     - cd /home/travis/build/TotallyRealOrganization/ApartmentsOnline/frontend
     - npm install -g @angular/cli
     - npm install
    script:
     #- ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
     - ng build --prod --base-href https://github.com/TotallyRealOrganization/ApartmentsOnline.git
    workspaces:
     create:
      name: front
      path: /home/travis/build/TotallyRealOrganization/ApartmentsOnline
     
  - stage: backend
    language: java
    jdk: oraclejdk8
    git:
     clone: true
    workspaces:
     use: front
     create:
      name: back
      path: /home/travis/build/TotallyRealOrganization/ApartmentsOnline
    before_script:
     - ls
     - 
    script:
     - mvn package
  - stage: deployment 
    language: generic
    git:
     clone: false
     workspaces:
      use: back
    before_script:
     - cd /
     - cd /home/travis/build/TotallyRealOrganization/ApartmentsOnline
    services:
     - docker
    script:
     - docker build -t df_project2 .
    after_success:
     - docker login -u $DOCKER_USER -p $DOCKER_PASS
     - docker tag df_project2 $DOCKER_USER/df_project2:latest
     - docker push $DOCKER_USER/df_project2:latest
   
   
