notifications:
 email:
  - finchjavar@yahoo.com
services:
 - docker
before install:
 - docker build -t df_project2 .
 - docker run df_project2
stages:
 - frontend
 - backend

dist: trusty
sudo: required
branches:
 only:
  - master
jobs:
 include:
  - stage: frontend
    language: node_js
    node_js:
     - 10
    addons:
     chrome: stable
    before_script:
     - cd /
     - cd /home/travis/build/TotallyRealOrganization/ApartmentsOnline/frontend
     - npm install -g @angular/cli
     - npm install
    script:
     - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
     - ng build --prod --base-href https://github.com/TotallyRealOrganization/ApartmentsOnline.git
  - stage: backend
    language: java
    jdk: oraclejdk8
    before_script:
     - cd /
     - cd /home/travis/build/TotallyRealOrganization/ApartmentsOnline
    script:
     - mvn test
